version: "3.7"

services:
  brownbag:
    container_name: brownbag
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/brownbag"
      - "/brownbag/node_modules"
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
